//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiskWork.UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhiskWork.UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;ol&gt;&lt;li id=&quot;analysis&quot; class=&quot;analysis&quot;&gt;&lt;h1&gt;
        ///				Analysis
        ///			&lt;/h1&gt;&lt;ol&gt;&lt;li id=&quot;analysis.inprocess&quot; class=&quot;workstep step-cr inprocess&quot;&gt;&lt;ol&gt;&lt;li id=&quot;cr1&quot; class=&quot;workitem cr&quot;&gt;&lt;/li&gt;&lt;li id=&quot;cr2&quot; class=&quot;workitem cr&quot;&gt;&lt;/li&gt;&lt;li id=&quot;cr3&quot; class=&quot;workitem cr&quot;&gt;&lt;/li&gt;&lt;/ol&gt;&lt;/li&gt;&lt;li id=&quot;analysis.done&quot; class=&quot;workstep step-cr done&quot;&gt;&lt;ol&gt;&lt;li id=&quot;cr4&quot; class=&quot;workitem cr&quot;&gt;&lt;/li&gt;&lt;/ol&gt;&lt;/li&gt;&lt;/ol&gt;&lt;/li&gt;&lt;li id=&quot;development&quot; class=&quot;development&quot;&gt;&lt;h1&gt;
        ///				Development
        ///			&lt;/h1&gt;&lt;ol&gt;&lt;li id=&quot;development.inprocess&quot; class=&quot;inprocess [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullFeatureTest {
            get {
                return ResourceManager.GetString("FullFeatureTest", resourceCulture);
            }
        }
    }
}
